# Generated by Django 4.0 on 2021-12-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=40)),
                ('serving', models.CharField(max_length=40)),
            ],
        ),
    ]
