# Generated by Django 4.0 on 2021-12-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('learn', models.CharField(max_length=50)),
                ('design', models.CharField(max_length=20)),
            ],
        ),
    ]
