# Generated by Django 4.0 on 2021-12-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code',
            new_name='Cod',
        ),
    ]
