# Generated by Django 4.0 on 2021-12-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_code_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('breed', models.CharField(max_length=50)),
            ],
        ),
    ]
