# Generated by Django 4.0 on 2021-12-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_robot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cel', models.CharField(max_length=40)),
                ('wish', models.CharField(max_length=50)),
                ('tq', models.CharField(max_length=40)),
            ],
        ),
    ]
