# Generated by Django 4.0 on 2021-12-31 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
